#!/bin/bash

# Check that the environment variable has been set correctly
if [ -z "$SECRETS_BUCKET_NAME" ]; then
  echo >&2 'error: missing SECRETS_BUCKET_NAME environment variable'
  exit 1
fi

# Load the S3 secrets file contents into the environment variables
aws s3 cp s3://${SECRETS_BUCKET_NAME}/private.pem private.pem

export JAP_PRIVATE_KEY_PATH=`pwd`/private.pem

eval "${@:1}"
